import React, { useState, useEffect, useCallback } from 'react';
import {
  IonPage,
  IonContent,
  IonHeader,
  IonToolbar,
  IonButtons,
  IonMenuButton,
  IonIcon,
  IonModal,
  IonTitle,
  IonButton,
  useIonViewWillEnter,
} from '@ionic/react';
import {
  notificationsOutline,
  helpCircleOutline,
  searchOutline,
  filterOutline,
  calendarOutline,
  eyeOutline,
  pencilOutline,
  checkmarkCircleOutline,
  timeOutline,
  documentTextOutline,
  imageOutline,
  alertCircleOutline,
  flagOutline,
  trendingUpOutline,
  downloadOutline,
  printOutline,
  addOutline,
  chevronForwardOutline,
  star,
  mailOutline,
  callOutline,
  waterOutline,
  trashOutline,
  cashOutline,
  personOutline,
  cloudUploadOutline,
  closeOutline,
  shieldCheckmarkOutline,
  swapHorizontalOutline,
  barChartOutline,
  receiptOutline,
  settingsOutline,
  arrowBackOutline,
  locationOutline,
  medkitOutline,
  peopleOutline,
  closeCircleOutline,
} from 'ionicons/icons';
import { useHistory } from 'react-router-dom';
import { useAuthStore } from '../../store/auth.store';
import { ROUTES } from '../../constants/routes.constant';
import { getPatients, deletePatient, getPatientStats } from '../../api/patient.api';
import { getHealers } from '../../api/healer.api';
import '../super-admin/super-admin.css';
import './branch-admin.css';

// Highly comprehensive Patient structure matching all requirements
export interface Patient {
  id: string; // Patient ID (DB UUID)
  patientId: string; // Display ID (e.g. PAT-xxxx)
  name: string; // Patient Name
  photoUrl?: string; // Profile Photo Mock
  initials: string;
  avatarColor: string;
  mobile: string; // Mobile Number
  email: string; // Email Address
  gender: 'Male' | 'Female'; // Gender
  age: number; // Age
  bloodGroup: string; // Blood Group
  dateOfBirth: string; // Date of Birth
  occupation: string; // Occupation
  assignedHealer: string; // Assigned Healer
  regDate: string; // Registration Date
  lastVisitDate: string; // Last Visit Date
  status: 'Active' | 'On Hold' | 'Completed' | 'Inactive'; // Status
  address?: string;
  treatmentType?: string;
  emergencyContact: {
    name: string;
    relation: string;
    mobile: string;
  };
  medicalInfo: {
    conditions: string[];
    allergies: string[];
    medications: string[];
    notes: string;
  };
  appointments: {
    id: string;
    date: string;
    time: string;
    healer: string;
    status: 'Pending' | 'Confirmed' | 'Completed' | 'Cancelled' | 'Rescheduled';
    remindersEnabled: boolean;
  }[];
  sessions: {
    id: string;
    healer: string;
    status: 'Scheduled' | 'Ongoing' | 'Completed' | 'Cancelled';
    notes: string;
    followUpDate?: string;
  }[];
  financials: {
    balanceDue: number;
    invoices: {
      id: string;
      date: string;
      amount: number;
      status: 'Paid' | 'Unpaid' | 'Partial';
      method?: 'Cash' | 'UPI' | 'Card' | 'Bank Transfer';
    }[];
  };
  documents: {
    id: string;
    name: string;
    category: 'Doctor Report' | 'Lab Report' | 'Consultation Note' | 'Other';
    size: string;
    date: string;
    type: 'pdf' | 'image';
    uploadedBy: string;
  }[];
  activityLogs: {
    action: string;
    timestamp: string;
    category: 'login' | 'appointment' | 'payment' | 'profile_update' | 'session_update';
  }[];
  statusHistory: {
    prevStatus: string;
    newStatus: string;
    changedBy: string;
    timestamp: string;
  }[];
  healerHistory: {
    prevHealer: string;
    newHealer: string;
    changedBy: string;
    timestamp: string;
  }[];
  feedback: {
    sessionRef: string;
    rating: number;
    comment: string;
    date: string;
  }[];
  credentials?: {
    username: string;
    passwordAutoGenerated: string;
    smsSent: boolean;
    emailSent: boolean;
  };
  branchId?: string;
}

const PatientsPage: React.FC = () => {
  const { user } = useAuthStore();
  const history = useHistory();

  // Strict Scoping / Access Control Check
  const isBranchAdmin = user?.role === 'BRANCH_ADMIN';

  const customStyles = {
    formCard: {
      background: '#ffffff',
      borderRadius: '16px',
      padding: '28px',
      border: '1px solid #e2e8f0',
      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.025)',
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '20px',
    },
    subHeader: {
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
      fontSize: '18px',
      fontWeight: 700,
      color: 'var(--ba-color-primary)',
      marginTop: '4px',
      marginBottom: '12px',
    },
    subHeaderIcon: {
      color: 'var(--ba-color-primary)',
      fontSize: '22px',
    },
    label: {
      fontSize: '11px',
      fontWeight: 800,
      color: '#475569',
      letterSpacing: '0.5px',
      marginBottom: '6px',
      textTransform: 'uppercase' as const,
    },
    grayInput: {
      background: '#f8fafc',
      border: '1px solid #e2e8f0',
      borderRadius: '8px',
      padding: '12px 16px',
      fontSize: '14px',
      color: '#1e293b',
      outline: 'none',
      width: '100%',
      transition: 'all 0.2s ease',
    },
    grayTextarea: {
      background: '#f8fafc',
      border: '1px solid #e2e8f0',
      borderRadius: '8px',
      padding: '12px 16px',
      fontSize: '14px',
      color: '#1e293b',
      outline: 'none',
      width: '100%',
      resize: 'none' as const,
      lineHeight: 1.5,
      transition: 'all 0.2s ease',
    },
    dashedUpload: {
      background: '#f8fafc',
      border: '1px dashed #cbd5e1',
      borderRadius: '8px',
      height: '38px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      cursor: 'pointer',
      width: '100%',
      transition: 'all 0.2s ease',
    },
    dashedUploadActive: {
      background: '#f0fdf4',
      border: '1px solid #a7f3d0',
      borderRadius: '8px',
      height: '38px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '0 12px',
      cursor: 'pointer',
      width: '100%',
    },
    statusCard: {
      display: 'flex',
      flexDirection: 'column' as const,
      alignItems: 'center',
      justifyContent: 'center',
      padding: '20px 12px',
      borderRadius: '12px',
      cursor: 'pointer',
      textAlign: 'center' as const,
      transition: 'all 0.2s ease',
      width: '100%',
      minHeight: '104px',
    },
  };

  // Primary State
  const [patients, setPatients] = useState<Patient[]>([]);
  const [healersList, setHealersList] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [deleteConfirmPatient, setDeleteConfirmPatient] = useState<any | null>(null);
  const [stats, setStats] = useState({ activeCases: 0, totalRegistered: 0, pendingBalance: 0 });

  const fetchStats = useCallback(async () => {
    try {
      const response = await getPatientStats();
      if (response.success && response.data) {
        setStats(response.data);
      }
    } catch (error) {
      console.error('Error fetching patient stats:', error);
    }
  }, []);

  // ── Fetch patients from DB ───────────────────────────────────────────────
  const fetchPatients = useCallback(async () => {
    setIsLoading(true);
    try {
      fetchStats();
      const response = await getPatients();
      const apiPatients = Array.isArray(response) ? response : (response.data || response);
      if (Array.isArray(apiPatients)) {
        const formattedPatients = apiPatients.map((p: any) => {
          // Dynamic Documents
          const documentsList = [];
          if (p.medicalReport) {
            documentsList.push({
              id: 'med-rep',
              name: p.medicalReport,
              category: 'Doctor Report' as const,
              size: 'N/A',
              date: p.updatedAt ? p.updatedAt.split('T')[0] : 'N/A',
              type: p.medicalReport.endsWith('.pdf') ? 'pdf' as const : 'image' as const,
              uploadedBy: 'System',
            });
          }
          if (p.labReport) {
            documentsList.push({
              id: 'lab-rep',
              name: p.labReport,
              category: 'Lab Report' as const,
              size: 'N/A',
              date: p.updatedAt ? p.updatedAt.split('T')[0] : 'N/A',
              type: p.labReport.endsWith('.pdf') ? 'pdf' as const : 'image' as const,
              uploadedBy: 'System',
            });
          }
          if (p.prescription) {
            documentsList.push({
              id: 'prescription',
              name: p.prescription,
              category: 'Other' as const,
              size: 'N/A',
              date: p.updatedAt ? p.updatedAt.split('T')[0] : 'N/A',
              type: p.prescription.endsWith('.pdf') ? 'pdf' as const : 'image' as const,
              uploadedBy: 'System',
            });
          }
          if (p.idProof) {
            documentsList.push({
              id: 'id-proof',
              name: p.idProof,
              category: 'Other' as const,
              size: 'N/A',
              date: p.updatedAt ? p.updatedAt.split('T')[0] : 'N/A',
              type: p.idProof.endsWith('.pdf') ? 'pdf' as const : 'image' as const,
              uploadedBy: 'System',
            });
          }

          // Dynamic Sessions
          const sessionsList = p.sessions || [];
          const mappedSessions = sessionsList.map((s: any) => ({
            id: s.id,
            healer: s.healer?.name || p.healer?.name || 'None',
            status: s.status ? (s.status.charAt(0).toUpperCase() + s.status.slice(1)) as any : 'Scheduled',
            notes: s.notes || 'No notes entered.',
            followUpDate: s.updatedAt ? s.updatedAt.split('T')[0] : undefined,
          }));

          // Dynamic Invoices & financials
          const invoices = sessionsList.map((s: any) => {
            const amount = Number(s.totalAmount || 0);
            const status = s.paymentStatus === 'paid' ? 'Paid' as const : s.paymentStatus === 'partial' ? 'Partial' as const : 'Unpaid' as const;
            const paid = s.payment ? Number(s.payment.amount || 0) : 0;
            const outstanding = status === 'Paid' ? 0 : status === 'Partial' ? Math.max(0, amount - paid) : amount;
            
            return {
              id: s.id,
              date: s.sessionDate ? s.sessionDate.split('T')[0] : 'N/A',
              amount: amount,
              paid: paid,
              outstanding: outstanding,
              status: status,
              method: s.paymentMethod === 'cash' ? 'Cash' as const : s.paymentMethod === 'upi' ? 'UPI' as const : s.paymentMethod === 'card' ? 'Card' as const : s.paymentMethod === 'bank_transfer' ? 'Bank Transfer' as const : undefined,
            };
          });

          const balanceDue = invoices.reduce((sum: number, inv: any) => sum + inv.outstanding, 0);

          // Feedbacks
          const feedbacks = p.feedbacks || [];
          const mappedFeedback = feedbacks.map((f: any) => ({
            sessionRef: f.id,
            rating: f.rating || 5,
            comment: f.comment || '',
            date: f.createdAt ? f.createdAt.split('T')[0] : 'N/A',
          }));

          return {
            id: p.id,
            patientId: p.patientId || p.id,
            name: p.name,
            initials: p.name ? p.name.split(' ').map((n: string) => n[0]).join('').slice(0, 2).toUpperCase() : 'PT',
            avatarColor: ['#0f5b4b', '#1e3a8a', '#b45309', '#7c3aed', '#db2777'][Math.floor(Math.random() * 5)],
            mobile: p.phone || p.mobile || '',
            email: p.email || '',
            gender: p.gender || 'Female',
            age: p.age || 30,
            bloodGroup: p.bloodGroup || 'O+',
            dateOfBirth: p.dob || p.dateOfBirth || '',
            occupation: p.occupation || '',
            assignedHealer: p.healer?.name || p.assignedHealer || 'None',
            regDate: p.createdAt ? p.createdAt.split('T')[0] : new Date().toISOString().split('T')[0],
            lastVisitDate: p.updatedAt ? p.updatedAt.split('T')[0] : new Date().toISOString().split('T')[0],
            status: p.status ? (p.status.charAt(0).toUpperCase() + p.status.slice(1)) as any : 'Active',
            address: p.address || '',
            treatmentType: p.treatmentType || '',
            emergencyContact: {
              name: p.emergencyContact || 'Emergency Contact',
              relation: 'Family',
              mobile: '',
            },
            medicalInfo: {
              conditions: p.medicalHistory ? p.medicalHistory.split(',').map((c: string) => c.trim()) : ['None recorded'],
              allergies: ['No known allergies'],
              medications: [],
              notes: 'No specialized clinical notes entered.',
            },
            appointments: [],
            sessions: mappedSessions,
            financials: { balanceDue, invoices },
            documents: documentsList,
            activityLogs: [
              { action: 'Profile loaded from database node', timestamp: 'Just now', category: 'login' as const }
            ],
            statusHistory: [],
            healerHistory: [],
            feedback: mappedFeedback,
            branchId: p.branchId || '',
          };
        });
        setPatients(formattedPatients);
        if (formattedPatients.length > 0) {
          setSelectedPatientId(prev => {
            const exists = formattedPatients.some(pt => pt.id === prev);
            return exists ? prev : formattedPatients[0].id;
          });
        }
      }
    } catch (error) {
      console.error('Error fetching patients:', error);
    } finally {
      setIsLoading(false);
    }
  }, []);

  // ── Fetch healers (one-time on mount) ────────────────────────────────────
  useEffect(() => {
    const fetchHealers = async () => {
      try {
        const response = await getHealers();
        const apiHealers = Array.isArray(response) ? response : (response.data || response);
        if (Array.isArray(apiHealers)) {
          setHealersList(apiHealers);
        }
      } catch (error) {
        console.error('Error fetching healers:', error);
      }
    };
    fetchPatients();
    fetchHealers();

    // Removed aggressive polling to fix Too Many Requests (429) rate limits.
    // Data is still fetched initially and via useIonViewWillEnter.
    return () => {
    };
  }, [fetchPatients, fetchStats]);

  // ── Re-fetch patients every time this page becomes active ────────────────
  // This ensures the list is always up-to-date after registration / edits.
  useIonViewWillEnter(() => {
    fetchPatients();
  });

  // Selected Patient Workspace
  const [selectedPatientId, setSelectedPatientId] = useState<string>('');
  const [viewMode, setViewMode] = useState<'list' | 'detail' | 'edit'>('list');

  // Search & Filter & Sorting state
  const [searchQuery, setSearchQuery] = useState('');
  const [genderFilter, setGenderFilter] = useState('All');
  const [statusFilter, setStatusFilter] = useState('All');
  const [healerFilter, setHealerFilter] = useState('All');
  const [sortBy, setSortBy] = useState('Newest');

  // Modals state
  const [showAddModal, setShowAddModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);

  // Form states
  const [newPatient, setNewPatient] = useState({
    name: '',
    mobile: '',
    email: '',
    gender: 'Female' as 'Male' | 'Female',
    age: 30,
    bloodGroup: 'O+',
    dateOfBirth: '',
    occupation: '',
    assignedHealer: 'None',
    emergencyName: '',
    emergencyRelation: '',
    emergencyMobile: '',
    conditions: '',
    allergies: '',
    notes: '',
  });

  const [editForm, setEditForm] = useState<Patient | null>(null);

  // Branch Name details
  const userName = user?.name || `${user?.firstName || ''} ${user?.lastName || ''}`.trim() || 'Aria Seraphina';
  const nameParts = userName.split(' ');
  const displayName = nameParts.length > 1 ? `${nameParts[0]} ${nameParts[1][0]}.` : userName;
  const userInitials = user
    ? `${user.name?.[0] || user.firstName?.[0] || 'B'}${user.name?.split(' ')?.[1]?.[0] || user.lastName?.[0] || 'A'}`.toUpperCase()
    : 'BA';

  const rawBranch = typeof user?.branch === 'object' && user?.branch !== null
    ? (user.branch as any).name
    : (user?.branch || 'Mumbai');
  const branchName = rawBranch.toLowerCase().includes('branch') ? rawBranch : `${rawBranch} Branch`;

  // Filter & Sort Logic
  const filteredPatients = patients.filter((p) => {
    const matchesSearch =
      p.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      p.mobile.includes(searchQuery) ||
      p.id.toLowerCase().includes(searchQuery.toLowerCase()) ||
      p.email.toLowerCase().includes(searchQuery.toLowerCase());

    const matchesGender = genderFilter === 'All' || p.gender === genderFilter;
    const matchesStatus = statusFilter === 'All' || p.status === statusFilter;
    const matchesHealer = healerFilter === 'All' || p.assignedHealer === healerFilter;

    return matchesSearch && matchesGender && matchesStatus && matchesHealer;
  });

  const sortedPatients = [...filteredPatients].sort((a, b) => {
    if (sortBy === 'Newest') {
      return new Date(b.regDate).getTime() - new Date(a.regDate).getTime();
    }
    if (sortBy === 'Alphabetical') {
      return a.name.localeCompare(b.name);
    }
    if (sortBy === 'Recent Visit') {
      return new Date(b.lastVisitDate).getTime() - new Date(a.lastVisitDate).getTime();
    }
    if (sortBy === 'Reg Date') {
      return new Date(a.regDate).getTime() - new Date(b.regDate).getTime();
    }
    return 0;
  });

  const selectedPatient = patients.find((p) => p.id === selectedPatientId) || patients[0];

  useEffect(() => {
    if (selectedPatient) {
      setEditForm({ ...selectedPatient });
    }
  }, [selectedPatientId, viewMode, patients]);

  if (!isBranchAdmin) {
    return (
      <IonPage className="sa-page">
        <IonContent className="sa-page__content" fullscreen>
          <div className="db-access-restricted-container">
            <div className="db-access-restricted-card">
              <div className="db-access-restricted-icon">
                <IonIcon icon={alertCircleOutline} />
              </div>
              <div className="db-access-restricted-details">
                <span className="db-access-restricted-title">Unauthorized Node Access</span>
                <p className="db-access-restricted-desc">
                  Access Denied. The Patient Management workspace is restricted exclusively to authorized Branch Admin users. You do not possess the required credentials to access this branch data.
                </p>
              </div>
            </div>
          </div>
        </IonContent>
      </IonPage>
    );
  }

  // Handle Add Patient Action
  const handleAddPatientSubmit = () => {
    if (!newPatient.name || !newPatient.mobile || !newPatient.email) {
      alert('Please fill in required fields.');
      return;
    }

    const patientId = `#P-${Math.floor(1000 + Math.random() * 9000)}`;
    const hasHealer = newPatient.assignedHealer && newPatient.assignedHealer !== 'None';
    const username = newPatient.name.toLowerCase().replace(/\s+/g, '_') + `_${Math.floor(Math.random() * 100)}`;
    const passwordAutoGenerated = `PHMS-${Math.random().toString(36).substring(2, 7)}#`;
    const credentials = hasHealer ? {
      username,
      passwordAutoGenerated,
      smsSent: true,
      emailSent: true
    } : undefined;

    const timestampString = new Date().toISOString().replace('T', ' ').substring(0, 19);

    const initialActivityLogs = [
      { action: 'Patient registered folder initialized', timestamp: 'Just now', category: 'profile_update' as const },
    ];
    if (hasHealer) {
      initialActivityLogs.unshift(
        { action: `SMS login credentials dispatched for username: ${username}`, timestamp: 'Just now', category: 'profile_update' as const },
        { action: `Email login credentials dispatched for email: ${newPatient.email}`, timestamp: 'Just now', category: 'profile_update' as const }
      );
    }

    const added: Patient = {
      id: patientId,
      patientId: patientId,
      name: newPatient.name,
      initials: newPatient.name.split(' ').map((n) => n[0]).join('').slice(0, 2).toUpperCase(),
      avatarColor: ['#0f5b4b', '#1e3a8a', '#b45309', '#7c3aed', '#db2777'][Math.floor(Math.random() * 5)],
      mobile: newPatient.mobile,
      email: newPatient.email,
      gender: newPatient.gender,
      age: Number(newPatient.age),
      bloodGroup: newPatient.bloodGroup,
      dateOfBirth: newPatient.dateOfBirth,
      occupation: newPatient.occupation,
      assignedHealer: newPatient.assignedHealer,
      regDate: new Date().toISOString().split('T')[0],
      lastVisitDate: new Date().toISOString().split('T')[0],
      status: 'Active',
      emergencyContact: {
        name: newPatient.emergencyName || 'Emergency Name',
        relation: newPatient.emergencyRelation || 'Family',
        mobile: newPatient.emergencyMobile || '9876543210',
      },
      medicalInfo: {
        conditions: newPatient.conditions ? newPatient.conditions.split(',').map((c) => c.trim()) : ['None recorded'],
        allergies: newPatient.allergies ? newPatient.allergies.split(',').map((c) => c.trim()) : ['No known allergies'],
        medications: ['Pranic treatment protocols'],
        notes: newPatient.notes || 'No specialized clinical notes entered.',
      },
      appointments: [],
      sessions: [],
      financials: { balanceDue: 0, invoices: [] },
      documents: [],
      activityLogs: initialActivityLogs,
      statusHistory: [
        { prevStatus: 'None', newStatus: 'Active', changedBy: displayName, timestamp: timestampString }
      ],
      healerHistory: [
        { prevHealer: 'None', newHealer: newPatient.assignedHealer, changedBy: displayName, timestamp: timestampString }
      ],
      feedback: [],
      credentials,
      branchId: typeof user?.branch === 'object' && user?.branch !== null 
          ? (user.branch as any).id 
          : (user as any)?.branchId || undefined,
    };

    setPatients([added, ...patients]);
    setSelectedPatientId(patientId);
    setNewPatient({
      name: '',
      mobile: '',
      email: '',
      gender: 'Female',
      age: 30,
      bloodGroup: 'O+',
      dateOfBirth: '',
      occupation: '',
      assignedHealer: 'None',
      emergencyName: '',
      emergencyRelation: '',
      emergencyMobile: '',
      conditions: '',
      allergies: '',
      notes: '',
    });
    setShowAddModal(false);
  };

  // Handle Edit Patient Action
  const handleEditPatientSubmit = (updatedPatient?: Patient) => {
    const patientToSave = updatedPatient || editForm;
    if (!patientToSave) return;
    const oldPatient = patients.find((p) => p.id === patientToSave.id) || selectedPatient;
    const timestampString = new Date().toISOString().replace('T', ' ').substring(0, 19);

    let updatedHealerHistory = [...(patientToSave.healerHistory || [])];
    let updatedStatusHistory = [...(patientToSave.statusHistory || [])];
    let updatedActivityLogs = [...(patientToSave.activityLogs || [])];
    let credentials = patientToSave.credentials;

    // Detect healer change
    if (patientToSave.assignedHealer !== oldPatient.assignedHealer) {
      updatedHealerHistory.unshift({
        prevHealer: oldPatient.assignedHealer || 'None',
        newHealer: patientToSave.assignedHealer,
        changedBy: displayName,
        timestamp: timestampString,
      });
      updatedActivityLogs.unshift({
        action: `Healer assignment updated: [${oldPatient.assignedHealer || 'None'}] ➔ [${patientToSave.assignedHealer}]`,
        timestamp: 'Just now',
        category: 'profile_update' as const,
      });

      // Trigger credentials generation if unlocking from None
      const wasNone = !oldPatient.assignedHealer || oldPatient.assignedHealer === 'None';
      const isNowAssigned = patientToSave.assignedHealer && patientToSave.assignedHealer !== 'None';
      if (wasNone && isNowAssigned && !credentials) {
        const username = patientToSave.name.toLowerCase().replace(/\s+/g, '_') + `_${Math.floor(Math.random() * 100)}`;
        const passwordAutoGenerated = `PHMS-${Math.random().toString(36).substring(2, 7)}#`;
        credentials = {
          username,
          passwordAutoGenerated,
          smsSent: true,
          emailSent: true,
        };
        updatedActivityLogs.unshift(
          { action: `SMS login credentials dispatched for username: ${username}`, timestamp: 'Just now', category: 'profile_update' as const },
          { action: `Email login credentials dispatched for email: ${patientToSave.email}`, timestamp: 'Just now', category: 'profile_update' as const }
        );
      }
    }

    // Detect status change
    if (patientToSave.status !== oldPatient.status) {
      updatedStatusHistory.unshift({
        prevStatus: oldPatient.status || 'None',
        newStatus: patientToSave.status,
        changedBy: displayName,
        timestamp: timestampString,
      });
      updatedActivityLogs.unshift({
        action: `Patient status transitioned: [${oldPatient.status}] ➔ [${patientToSave.status}]`,
        timestamp: 'Just now',
        category: 'profile_update' as const,
      });
    }

    updatedActivityLogs.unshift({
      action: 'Personal information & medical records updated',
      timestamp: 'Just now',
      category: 'profile_update' as const,
    });

    const saved: Patient = {
      ...patientToSave,
      credentials,
      healerHistory: updatedHealerHistory,
      statusHistory: updatedStatusHistory,
      activityLogs: updatedActivityLogs,
    };

    setPatients(patients.map((p) => (p.id === patientToSave.id ? saved : p)));
    setShowEditModal(false);
  };


  // Global Analytics metrics calculated dynamically
  const activeCount = patients.filter((p) => p.status === 'Active').length;
  const mtdRegistered = patients.length;
  const pendingBalanceSum = patients.reduce((sum, p) => sum + (p.financials?.balanceDue || 0), 0);

  return (
    <IonPage className="sa-page">
      <IonHeader className="ion-no-border">
        <IonToolbar className="sa-page__toolbar">
          <IonButtons slot="start">
            <IonMenuButton />
          </IonButtons>
          <IonTitle className="sa-page__toolbar-title">Patient Management</IonTitle>
          <IonButtons slot="end">
            <div className="sa-page__toolbar-actions">
              
              <IonButton fill="clear">
                <IonIcon icon={notificationsOutline} />
              </IonButton>
              <div className="sa-page__toolbar-avatar">{userInitials}</div>
            </div>
          </IonButtons>
        </IonToolbar>
      </IonHeader>

      <IonContent className="sa-page__content" fullscreen>
        <div className="sa-page__body">
          <div className="ba-patients-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
            <p className="sa-page__subtitle" style={{ margin: 0 }}>
              Patient Records, Medical Workflows and Session Tracking
            </p>
            {viewMode === 'list' && (
              <button className="sa-btn sa-btn--primary" onClick={() => history.push('/branch-admin/patients/register')} style={{ display: 'flex', alignItems: 'center', gap: '6px', padding: '8px 16px', fontSize: '13px' }}>
                <IonIcon icon={addOutline} /> Add New Patient
              </button>
            )}
          </div>

          {viewMode === 'list' && (
            <>
              {/* =======================================================
                  SECTION 1: CLINICAL STATS PREVIEW PRE-CHECKS RIBBON
                 ======================================================= */}
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '16px', marginBottom: '24px' }}>
                <div className="ba-widget-card" style={{ background: '#ffffff', borderRadius: '12px', padding: '16px', boxShadow: '0 1px 3px rgba(0,0,0,0.02)', borderLeft: '4px solid #10b981', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                  <span className="ba-widget-title" style={{ fontSize: '11px', color: '#64748b', fontWeight: 700, textTransform: 'uppercase' }}>Active Cases</span>
                  <span className="ba-widget-count" style={{ fontSize: '24px', fontWeight: 800, color: '#0f172a' }}>{activeCount}</span>
                </div>
                <div className="ba-widget-card" style={{ background: '#ffffff', borderRadius: '12px', padding: '16px', boxShadow: '0 1px 3px rgba(0,0,0,0.02)', borderLeft: '4px solid #1e3a8a', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                  <span className="ba-widget-title" style={{ fontSize: '11px', color: '#64748b', fontWeight: 700, textTransform: 'uppercase' }}>Total Registered</span>
                  <span className="ba-widget-count" style={{ fontSize: '24px', fontWeight: 800, color: '#0f172a' }}>{mtdRegistered}</span>
                </div>
                {/* <div className="ba-widget-card" style={{ background: '#ffffff', borderRadius: '12px', padding: '16px', boxShadow: '0 1px 3px rgba(0,0,0,0.02)', borderLeft: '4px solid #f59e0b', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                  <span className="ba-widget-title" style={{ fontSize: '11px', color: '#64748b', fontWeight: 700, textTransform: 'uppercase' }}>Daily Appts Queue</span>
                  <span className="ba-widget-count" style={{ fontSize: '24px', fontWeight: 800, color: '#0f172a' }}>18</span>
                </div>
                <div className="ba-widget-card" style={{ background: '#ffffff', borderRadius: '12px', padding: '16px', boxShadow: '0 1px 3px rgba(0,0,0,0.02)', borderLeft: '4px solid #8b5cf6', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                  <span className="ba-widget-title" style={{ fontSize: '11px', color: '#64748b', fontWeight: 700, textTransform: 'uppercase' }}>Documents Vaulted</span>
                  <span className="ba-widget-count" style={{ fontSize: '24px', fontWeight: 800, color: '#0f172a' }}>24</span>
                </div> */}
                <div className="ba-widget-card" style={{ background: '#ffffff', borderRadius: '12px', padding: '16px', boxShadow: '0 1px 3px rgba(0,0,0,0.02)', borderLeft: '4px solid #ef4444', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                  <span className="ba-widget-title" style={{ fontSize: '11px', color: '#64748b', fontWeight: 700, textTransform: 'uppercase' }}>Pending Balance</span>
                  <span className="ba-widget-count" style={{ fontSize: '24px', fontWeight: 800, color: '#0f172a' }}>₹{pendingBalanceSum.toFixed(2)}</span>
                </div>
              </div>

              {/* ==========================================
                  SECTION 2: ADVANCED FILTERING & SORTING BAR
                 ========================================== */}
              <div className="ba-patients-filters" style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '20px', flexWrap: 'wrap', justifyContent: 'space-between' }}>
                {/* Search Bar Input */}
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px', flex: 1, minWidth: '300px' }}>
                  <div className="sa-search" style={{ margin: 0, width: '100%', maxWidth: '550px' }}>
                    <IonIcon icon={searchOutline} />
                    <input
                      type="text"
                      placeholder="Search by ID, Name, Mobile, Email..."
                      value={searchQuery}
                      onChange={(e) => setSearchQuery(e.target.value)}
                    />
                  </div>
                </div>

                <div style={{ display: 'flex', alignItems: 'center', gap: '12px', flexWrap: 'wrap' }}>
                  {/* <div style={{ display: 'flex', alignItems: 'center', gap: '6px', background: '#f1f5f9', padding: '0 12px', borderRadius: '8px', fontSize: '12px', fontWeight: 700, color: '#334155', height: '36px', boxSizing: 'border-box' }}>
                    <IonIcon icon={filterOutline} />
                    <span>FILTERS</span>
                  </div> */}

                  {/* Gender filter select */}
                  <select
                    value={genderFilter}
                    onChange={(e) => setGenderFilter(e.target.value)}
                    style={{ height: '36px', padding: '0 12px', borderRadius: '8px', border: '1px solid #cbd5e1', background: '#ffffff', fontSize: '12px', color: '#475569', outline: 'none', fontWeight: 600, boxSizing: 'border-box' }}
                  >
                    <option value="All">All Genders</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                  </select>

                  {/* Status filter select */}
                  <select
                    value={statusFilter}
                    onChange={(e) => setStatusFilter(e.target.value)}
                    style={{ height: '36px', padding: '0 12px', borderRadius: '8px', border: '1px solid #cbd5e1', background: '#ffffff', fontSize: '12px', color: '#475569', outline: 'none', fontWeight: 600, boxSizing: 'border-box' }}
                  >
                    <option value="All">All Statuses</option>
                    <option value="Active">Active</option>
                    <option value="Inactive">Inactive</option>
                  </select>

                  {/* Healer filter select */}
                  <select
                    value={healerFilter}
                    onChange={(e) => setHealerFilter(e.target.value)}
                    style={{ height: '36px', padding: '0 12px', borderRadius: '8px', border: '1px solid #cbd5e1', background: '#ffffff', fontSize: '12px', color: '#475569', outline: 'none', fontWeight: 600, boxSizing: 'border-box' }}
                  >
                    <option value="All">All Healers</option>
                    {healersList.map((h: any) => (
                      <option key={h.id} value={h.name}>{h.name}</option>
                    ))}
                  </select>
                </div>
              </div>

              {/* ==========================================
                  SECTION 3: PATIENT REGISTRY TABLE (12 COLS)
                 ========================================== */}
              <div style={{ background: '#ffffff', borderRadius: '16px', padding: '20px', border: '1px solid #e2e8f0', marginBottom: '24px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
                  <div>
                    <h2 style={{ fontSize: '16px', fontWeight: 800, color: '#0f172a', margin: 0 }}>Branch Patient Directory</h2>
                    <p style={{ fontSize: '11px', color: '#64748b', margin: '2px 0 0 0' }}>Search and select patients to view complete profile folders</p>
                  </div>
                </div>

                {/* 12-Column Table Formats */}
                <div className="sa-table-container">
                  <table className="sa-table">
                    <thead>
                      <tr>
                        <th>PATIENT ID</th>
                        <th>PATIENT NAME</th>
                        <th>GENDER</th>
                        <th>AGE</th>
                        <th>ASSIGNED HEALER</th>
                        <th>REG DATE</th>
                        <th>STATUS</th>
                        <th style={{ textAlign: 'center' }}>ACTIONS</th>
                      </tr>
                    </thead>
                    <tbody>
                      {sortedPatients.length > 0 ? (
                        sortedPatients.map((patient) => {
                          const isSelected = patient.id === selectedPatientId;
                          return (
                            <tr
                              key={patient.id}
                              className={`sa-table-row ${isSelected ? 'sa-table-row--selected' : ''}`}
                              // onClick={() => { setSelectedPatientId(patient.id); setViewMode('detail'); }}
                              style={{ borderLeft: isSelected ? '4px solid #1f7a6a' : 'none' }}
                            >
                              <td style={{ fontWeight: '700', color: '#1f7a6a' }}>{patient.patientId}</td>
                              <td>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                                  <div
                                    style={{
                                      backgroundColor: patient.avatarColor,
                                      color: 'white',
                                      width: '32px',
                                      height: '32px',
                                      borderRadius: '50%',
                                      display: 'flex',
                                      alignItems: 'center',
                                      justifyContent: 'center',
                                      fontWeight: 'bold',
                                      fontSize: '11px',
                                    }}
                                  >
                                    {patient.initials}
                                  </div>
                                  <span style={{ fontWeight: '700', color: '#0f172a' }}>{patient.name}</span>
                                </div>
                              </td>
                              <td>{patient.gender}</td>
                              <td>{patient.age}</td>
                              
                              <td>{patient.assignedHealer}</td>
                              <td>{patient.regDate}</td>
                              <td>
                                <span className={`sa-badge ${patient.status === 'Active' ? 'sa-badge--active' : patient.status === 'On Hold' ? 'sa-badge--on-hold' : ''}`}>
                                  {patient.status}
                                </span>
                              </td>
                              <td style={{ textAlign: 'center' }} onClick={(e) => e.stopPropagation()}>
                                <div style={{ display: 'flex', gap: '16px', justifyContent: 'center' }}>
                                  <button title="View Patient" onClick={() => { history.push(ROUTES.BRANCH_ADMIN.PATIENT_DETAILS.replace(':id', encodeURIComponent(patient.id))); }} style={{ background: 'transparent', border: 'none', cursor: 'pointer', fontSize: '18px', color: '#64748b', padding: 0 }}>
                                    <IonIcon icon={eyeOutline} />
                                  </button>
                                  <button title="Edit Profile" onClick={() => { setSelectedPatientId(patient.id); history.push(ROUTES.BRANCH_ADMIN.EDIT_PATIENT.replace(':id', encodeURIComponent(patient.id))); }} style={{ background: 'transparent', border: 'none', cursor: 'pointer', fontSize: '18px', color: '#64748b', padding: 0 }}>
                                    <IonIcon icon={pencilOutline} />
                                  </button>
                                  <button title="Delete Patient" onClick={(e) => { e.stopPropagation(); setDeleteConfirmPatient(patient); }} style={{ background: 'transparent', border: 'none', cursor: 'pointer', fontSize: '18px', color: '#ef4444', padding: 0 }}>
                                    <IonIcon icon={trashOutline} />
                                  </button>
                                </div>
                              </td>
                            </tr>
                          );
                        })
                      ) : (
                        <tr>
                          <td colSpan={10} className="sa-table-empty">
                            No registered patients match your filters.
                          </td>
                        </tr>
                      )}
                    </tbody>
                  </table>
                </div>

                {/* Pagination Controls */}
                <div className="sa-pagination">
                  <span className="sa-pagination__info">
                    Showing {sortedPatients.length} of {patients.length} branch patients
                  </span>
                  <div className="sa-pagination__controls">
                    <button className="sa-pagination__btn" disabled>«</button>
                    <button className="sa-pagination__btn sa-pagination__btn--active">1</button>
                    <button className="sa-pagination__btn" disabled>»</button>
                  </div>
                </div>
              </div>

             
            </>
          )}

        </div>
      </IonContent>

      {/* ==========================================
          MODAL 1: ADD NEW PATIENT wizard
         ========================================== */}
      <IonModal isOpen={showAddModal} onDidDismiss={() => setShowAddModal(false)} className="sa-modal">
        <div className="sa-modal__content">
          <div className="sa-modal__header">
            <h2>Register New Patient folder</h2>
            <button className="sa-modal__close-btn" onClick={() => setShowAddModal(false)}>×</button>
          </div>
          <div className="sa-modal__body">
            <div className="st-form">
              {/* Row 1 */}
              <div className="st-form-row">
                <div className="st-form-group">
                  <label className="st-form-label">FULL PATIENT NAME *</label>
                  <input
                    type="text"
                    className="st-input"
                    placeholder="Full Name"
                    value={newPatient.name}
                    onChange={(e) => setNewPatient({ ...newPatient, name: e.target.value })}
                  />
                </div>
                <div className="st-form-group">
                  <label className="st-form-label">MOBILE NUMBER *</label>
                  <input
                    type="text"
                    className="st-input"
                    placeholder="10-digit Mobile"
                    value={newPatient.mobile}
                    onChange={(e) => setNewPatient({ ...newPatient, mobile: e.target.value })}
                  />
                </div>
              </div>

              {/* Row 2 */}
              <div className="st-form-row">
                <div className="st-form-group">
                  <label className="st-form-label">EMAIL ADDRESS *</label>
                  <input
                    type="email"
                    className="st-input"
                    placeholder="email@example.com"
                    value={newPatient.email}
                    onChange={(e) => setNewPatient({ ...newPatient, email: e.target.value })}
                  />
                </div>
                <div className="st-form-row" style={{ gap: '10px' }}>
                  <div className="st-form-group">
                    <label className="st-form-label">GENDER</label>
                    <select
                      className="st-input"
                      value={newPatient.gender}
                      onChange={(e) => setNewPatient({ ...newPatient, gender: e.target.value as any })}
                    >
                      <option value="Male">Male</option>
                      <option value="Female">Female</option>
                    </select>
                  </div>
                  <div className="st-form-group">
                    <label className="st-form-label">AGE</label>
                    <input
                      type="number"
                      className="st-input"
                      value={newPatient.age}
                      onChange={(e) => setNewPatient({ ...newPatient, age: Number(e.target.value) })}
                    />
                  </div>
                  <div className="st-form-group">
                    <label className="st-form-label">BLOOD GROUP</label>
                    <input
                      type="text"
                      className="st-input"
                      placeholder="e.g. O+"
                      value={newPatient.bloodGroup}
                      onChange={(e) => setNewPatient({ ...newPatient, bloodGroup: e.target.value })}
                    />
                  </div>
                </div>
              </div>

              {/* Row 2 - Additional Fields */}
              <div className="st-form-row">
                <div className="st-form-group">
                  <label className="st-form-label">DATE OF BIRTH</label>
                  <input
                    type="date"
                    className="st-input"
                    value={newPatient.dateOfBirth}
                    onChange={(e) => setNewPatient({ ...newPatient, dateOfBirth: e.target.value })}
                  />
                </div>
                <div className="st-form-group">
                  <label className="st-form-label">OCCUPATION</label>
                  <input
                    type="text"
                    className="st-input"
                    placeholder="Occupation"
                    value={newPatient.occupation}
                    onChange={(e) => setNewPatient({ ...newPatient, occupation: e.target.value })}
                  />
                </div>
              </div>

              {/* Row 3 */}
              <div className="st-form-row">
                <div className="st-form-group">
                  <label className="st-form-label">ASSIGNED CLINICAL HEALER</label>
                  <select
                    className="st-input"
                    value={newPatient.assignedHealer}
                    onChange={(e) => setNewPatient({ ...newPatient, assignedHealer: e.target.value })}
                  >
                    <option value="None">None (Unassigned)</option>
                    {healersList.map((h: any) => (
                      <option key={h.id} value={h.name}>{h.name}</option>
                    ))}
                  </select>
                </div>
              </div>

              <span className="pa-info-block-title" style={{ marginTop: '12px' }}>Emergency Contact</span>
              
              <div className="st-form-row">
                <div className="st-form-group">
                  <label className="st-form-label">CONTACT NAME</label>
                  <input
                    type="text"
                    className="st-input"
                    placeholder="Emergency Name"
                    value={newPatient.emergencyName}
                    onChange={(e) => setNewPatient({ ...newPatient, emergencyName: e.target.value })}
                  />
                </div>
                <div className="st-form-group">
                  <label className="st-form-label">RELATION</label>
                  <input
                    type="text"
                    className="st-input"
                    placeholder="Relation"
                    value={newPatient.emergencyRelation}
                    onChange={(e) => setNewPatient({ ...newPatient, emergencyRelation: e.target.value })}
                  />
                </div>
                <div className="st-form-group">
                  <label className="st-form-label">MOBILE NUMBER</label>
                  <input
                    type="text"
                    className="st-input"
                    placeholder="Emergency Mobile"
                    value={newPatient.emergencyMobile}
                    onChange={(e) => setNewPatient({ ...newPatient, emergencyMobile: e.target.value })}
                  />
                </div>
              </div>

              <span className="pa-info-block-title" style={{ marginTop: '12px' }}>Clinical Information</span>

              <div className="st-form-row">
                <div className="st-form-group">
                  <label className="st-form-label">HEALTH CONDITIONS (COMMA SEPARATED)</label>
                  <input
                    type="text"
                    className="st-input"
                    placeholder="e.g. Hypertension, Lower Back Pain"
                    value={newPatient.conditions}
                    onChange={(e) => setNewPatient({ ...newPatient, conditions: e.target.value })}
                  />
                </div>
                <div className="st-form-group">
                  <label className="st-form-label">ALLERGIES (COMMA SEPARATED)</label>
                  <input
                    type="text"
                    className="st-input"
                    placeholder="e.g. Lavender oil, Dust"
                    value={newPatient.allergies}
                    onChange={(e) => setNewPatient({ ...newPatient, allergies: e.target.value })}
                  />
                </div>
              </div>

              <div className="st-form-group">
                <label className="st-form-label">CLINICAL OBSERVATION NOTES</label>
                <textarea
                  className="st-textarea"
                  rows={2}
                  placeholder="Enter medical notes or healing specifics..."
                  value={newPatient.notes}
                  onChange={(e) => setNewPatient({ ...newPatient, notes: e.target.value })}
                />
              </div>
            </div>
          </div>
          <div className="sa-modal__footer">
            <button className="sa-btn sa-btn--outline" onClick={() => setShowAddModal(false)}>Cancel</button>
            <button className="sa-btn sa-btn--primary" onClick={handleAddPatientSubmit}>Add Patient</button>
          </div>
        </div>
      </IonModal>

      {/* ==========================================
          MODAL 2: EDIT PATIENT FORM
         ========================================== */}
      <IonModal isOpen={showEditModal} onDidDismiss={() => setShowEditModal(false)} className="sa-modal">
        <div className="sa-modal__content">
          <div className="sa-modal__header">
            <h2>Edit Patient Profile: {editForm?.name}</h2>
            <button className="sa-modal__close-btn" onClick={() => setShowEditModal(false)}>×</button>
          </div>
          <div className="sa-modal__body">
            {editForm && (
              <div className="st-form">
                <div className="st-form-row">
                  <div className="st-form-group">
                    <label className="st-form-label">FULL PATIENT NAME</label>
                    <input
                      type="text"
                      className="st-input"
                      value={editForm.name}
                      onChange={(e) => setEditForm({ ...editForm, name: e.target.value })}
                    />
                  </div>
                  <div className="st-form-group">
                    <label className="st-form-label">MOBILE NUMBER</label>
                    <input
                      type="text"
                      className="st-input"
                      value={editForm.mobile}
                      onChange={(e) => setEditForm({ ...editForm, mobile: e.target.value })}
                    />
                  </div>
                </div>

                <div className="st-form-row">
                  <div className="st-form-group">
                    <label className="st-form-label">EMAIL ADDRESS</label>
                    <input
                      type="email"
                      className="st-input"
                      value={editForm.email}
                      onChange={(e) => setEditForm({ ...editForm, email: e.target.value })}
                    />
                  </div>
                  <div className="st-form-row" style={{ gap: '10px' }}>
                    <div className="st-form-group">
                      <label className="st-form-label">AGE</label>
                      <input
                        type="number"
                        className="st-input"
                        value={editForm.age}
                        onChange={(e) => setEditForm({ ...editForm, age: Number(e.target.value) })}
                      />
                    </div>
                    <div className="st-form-group">
                      <label className="st-form-label">BLOOD GROUP</label>
                      <input
                        type="text"
                        className="st-input"
                        value={editForm.bloodGroup}
                        onChange={(e) => setEditForm({ ...editForm, bloodGroup: e.target.value })}
                      />
                    </div>
                    <div className="st-form-group">
                      <label className="st-form-label">CLINICAL STATUS</label>
                      <select
                        className="st-input"
                        value={editForm.status}
                        onChange={(e) => setEditForm({ ...editForm, status: e.target.value as any })}
                      >
                        <option value="Active">Active</option>
                        <option value="On Hold">On Hold</option>
                        <option value="Completed">Completed</option>
                        <option value="Inactive">Inactive</option>
                      </select>
                    </div>
                  </div>
                </div>

                <div className="st-form-row">
                  <div className="st-form-group">
                    <label className="st-form-label">ASSIGNED HEALER</label>
                    <select
                      className="st-input"
                      value={editForm.assignedHealer}
                      onChange={(e) => setEditForm({ ...editForm, assignedHealer: e.target.value })}
                    >
                      <option value="None">None (Unassigned)</option>
                      {healersList.map((h: any) => (
                        <option key={h.id} value={h.name}>{h.name}</option>
                      ))}
                    </select>
                  </div>
                </div>

                <span className="pa-info-block-title" style={{ marginTop: '12px' }}>Medical Notes</span>

                <div className="st-form-group">
                  <label className="st-form-label">CLINICAL PROFILE OVERVIEW</label>
                  <textarea
                    className="st-textarea"
                    rows={3}
                    value={editForm.medicalInfo.notes}
                    onChange={(e) => setEditForm({
                      ...editForm,
                      medicalInfo: { ...editForm.medicalInfo, notes: e.target.value }
                    })}
                  />
                </div>
              </div>
            )}
          </div>
          <div className="sa-modal__footer">
            <button className="sa-btn sa-btn--outline" onClick={() => setShowEditModal(false)}>Cancel</button>
            <button className="sa-btn sa-btn--primary" onClick={() => handleEditPatientSubmit()}>Save Changes</button>
          </div>
        </div>
      </IonModal>

      {/* ==========================================
          MODAL 3: CREATE APPOINTMENT
         ========================================== */}

      {/* Custom Delete Confirmation Modal */}
      {deleteConfirmPatient && (
        <div
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            zIndex: 9999,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            background: 'rgba(15, 23, 42, 0.6)',
            backdropFilter: 'blur(4px)',
          }}
        >
          <div
            style={{
              background: '#ffffff',
              borderRadius: '16px',
              border: '1px solid #e2e8f0',
              boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
              maxWidth: '400px',
              width: '90%',
              padding: '24px',
              textAlign: 'center',
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              gap: '16px',
            }}
          >
            <div
              style={{
                width: '56px',
                height: '56px',
                borderRadius: '50%',
                background: '#fee2e2',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <IonIcon
                icon={trashOutline}
                style={{ color: '#ef4444', fontSize: '28px' }}
              />
            </div>
            <div>
              <h3
                style={{
                  fontSize: '18px',
                  fontWeight: '800',
                  color: '#1f2937',
                  margin: '0 0 8px 0',
                }}
              >
                Confirm Deletion
              </h3>
              <p
                style={{
                  fontSize: '14px',
                  color: '#4b5563',
                  margin: 0,
                  lineHeight: 1.5,
                }}
              >
                Are you sure you want to delete patient <strong>{deleteConfirmPatient.name}</strong>?
                This action will remove their record from both the patients and users databases and cannot be undone.
              </p>
            </div>
            <div
              style={{
                display: 'flex',
                gap: '12px',
                width: '100%',
                marginTop: '8px',
              }}
            >
              <button
                onClick={() => setDeleteConfirmPatient(null)}
                style={{
                  flex: 1,
                  background: '#ffffff',
                  border: '1px solid #d1d5db',
                  borderRadius: '8px',
                  padding: '10px 16px',
                  fontSize: '14px',
                  fontWeight: 600,
                  color: '#374151',
                  cursor: 'pointer',
                  transition: 'background 0.2s',
                }}
              >
                Cancel
              </button>
              <button
                onClick={async () => {
                  const patientToDelete = deleteConfirmPatient;
                  setDeleteConfirmPatient(null);
                  try {
                    await deletePatient(patientToDelete.id);
                    setPatients(prev => prev.filter(p => p.id !== patientToDelete.id));
                  } catch (err: any) {
                    console.error('Failed to delete patient:', err);
                    alert(err.response?.data?.message || 'Failed to delete patient. Please try again.');
                  }
                }}
                style={{
                  flex: 1,
                  background: '#ef4444',
                  border: 'none',
                  borderRadius: '8px',
                  padding: '10px 16px',
                  fontSize: '14px',
                  fontWeight: 600,
                  color: '#ffffff',
                  cursor: 'pointer',
                  transition: 'background 0.2s',
                }}
              >
                Confirm Delete
              </button>
            </div>
          </div>
        </div>
      )}
    </IonPage>
  );
};

export default PatientsPage;